feat: Configure tools application registry category - EXO-61480 - Meeds-io/MPIs#37
Meeds-io/task pull request #155
Opened 2023-01-04 08:54 UTC by sofyenne

This change is going to add the tasks application under the tools application category

2023-01-05 14:46 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 15:44 UTC, azayati requested changes

2023-01-05 15:44 UTC, azayati commented on task-management/src/main/webapp/WEB-INF/conf/task-addon/application-configuration.xml
> +                    <field name="description"><string>Task  application</string></field>
```suggestion
                    <field name="description"><string>Task application</string></field>
```

2023-01-05 17:42 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 18:11 UTC, sofyenne commented on task-management/src/main/webapp/WEB-INF/conf/task-addon/application-configuration.xml
> +                    <field name="description"><string>Task  application</string></field>
done !

2023-01-06 10:26 UTC, azayati approved these changes
LGTM

2023-01-06 10:27 UTC, merged