Task-44573: Add the maximum number of characters counter for task description
Meeds-io/task pull request #8
Opened 2022-02-17 11:06 UTC by wassimmhamdi

Problem: The task description field has no indication on the description's maximum number of characters
Fix: we add the character counter to make a limitation of the task's description which is 2000 characters like the one of project description field, so we must make the add buttom disabled whem the title of the task is less thean 3 caracters or more than 1024 and the max of descreption is more than 2000 caracter

2022-02-18 16:08 UTC, azayati requested changes
see review

2022-02-18 16:08 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +      pureText = div.textContent || div.innerText || '';
- The param sent by the emited event has already treated by this same code, why doing the same treatment again ?
- You can directly the param isDescriptionValid

2022-02-18 16:08 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawerComponents/TaskDescriptionEditor.vue
> +      }
do you need to emit the event also from this watch ?

2022-02-18 16:08 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawerComponents/TaskDescriptionEditor.vue
> +      this.$root.$emit('max', val);
you can directly send as event parameter if the description is valid or not and use it directly when intercepting the emited event in TaskDrawer.vue

2022-02-18 16:08 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +    loadDescription(description) {
```suggestion
    isDescriptionValid(descriptionValid) {
```

2022-02-18 16:08 UTC, azayati commented on task-management/src/main/webapp/vue-app/taskDrawer/components/TaskDrawer.vue
> +    this.$root.$on('max', event => this.loadDescription(event));
```suggestion
    this.$root.$on('max', descriptionValid=> this.descriptionValid(event));
```

2022-02-21 09:11 UTC, closed without merging

2022-02-21 09:12 UTC, wassimmhamdi commented
closed for new commit and review